### PR TITLE
Added file permissions problem detection

### PR DESCRIPTION
**Pull request by richard512**
Gives a more easily understandable error message when there's a file permission problem

### CODE REVIEW

**Comment by richard512** [comment]
**Most likely fix** for these errors, for an Apache server running Linux:
```
sudo chown -R www-data:www-data server/php/files/
sudo chmod -R 755 server/php/files/
```

**Comment by richard512** [comment]
Just added the ability to detect mime types and to create thumbnails for uploaded videos.

**Comment by blueimp** [comment]
Thanks a lot for your contribution, @richard512 

Those are all nice features and I've added your repository to the [wiki](https://github.com/blueimp/jQuery-File-Upload/wiki) (under forks).

I hope it's fine for you that I prefer your work as a fork, as I want to keep my maintainer workload small and adding video thumbnail support would open up another swath of potential issues.

Thanks a lot though!

**Comment by myselfgaurav** [comment]
upload to upload video file getting error :  Empty file upload result

**Comment by richard512** [comment]
myselfgaurav: My first guess would be that the uploaded file is bigger than what the server is configured to allow. What does it do when you try to upload other, smaller files?

**Comment by myselfgaurav** [comment]
thanks i checked my server upload max file size if 150 mb , i was uploading file of 600 mb , but i think data is sent in chuk format so upload should work , do i have to do some setting to enable file chunking please guide

**Comment by richard512** [comment]
that'll do it. and, yeah, it should be able read in the chunks.

if not, you can try something like

http://stackoverflow.com/questions/7853467/uploading-a-file-in-chunks-using-html5

or

https://github.com/sthielen/BigUpload

**Comment by richard512** [comment]
If you arrive at a solution that works very well for you, please let me know. i'd be interested to hear.

**Pull request closed without merging**
