### PR TITLE
Added backend restriction for maximum number of image uploads

### PR DESCRIPTION
**Pull request by saurabh-sharma**
Added backend restrictions on number of file uploads allowed in single request.

when singleFileUploads: false

> User can override number of maximum files on client side. So a server check is required.

For solving the purpose and adding more reliability added a server side check which can be bundled with front end checks, and if front end checks fail or user tries to fiddle the javascript to bypass the checks, backend check can still serve the purpose.

### CODE REVIEW

**Comment by saurabh-sharma** [comment]
Error message update pending

**Comment by blueimp** [comment]
Thanks for your contribution, @saurabh-sharma 

Unfortunately, I don't think this is a good approach, as you only limit the number of parts in the multipart POST message, which doesn't have any perceivable benefit.
Users can still send an arbitrary number of files by sending multiple POST requests for example.
Without any user identification, it will not be possible to limit the number of files uploaded.

If you need to limit the number of files users can upload, you can already do this with the current version of the PHP library.
By making use of the options `user_dirs` and `max_number_of_files` you can effectively limit the number of files an individual user can upload.

**Comment by saurabh-sharma** [comment]
Thanks for the reply @blueimp 

I am not talking about the max number of files that can be uploaded in a directory, but I did mean about enforcing 1 file limit per upload, which can't be trusted from the client side! User can just fiddle the script and just skip the single file upload limit.

I agree with you on this one:
> Users can still send an arbitrary number of files by sending multiple POST requests for example.
> Without any user identification, it will not be possible to limit the number of files uploaded.

User can upload any no. of files (which can be restricted with the way you mentioned in above comment)

#3462 just adds an option for single file upload (I know it can be restricted from the front end using this process https://github.com/blueimp/jQuery-File-Upload/wiki/Frequently-Asked-Questions#how-to-limit-the-file-selection-so-users-can-only-select-one-file) to be restricted from backend as well.

And trust me, the front end option mentioned in the link above does not work with drag and drops at all.

And apart from all this, can you just enable the `issues` options for this repo? There's another serious vulnerability which needs attention.

**Comment by blueimp** [comment]
I understand that your pull request adds a restriction to limit the number of files handled in a single request. I simply see no benefit in doing so.
e.g. to limit request size, it's much better to use server settings, e.g. in Nginx or Apache, before it's handled by PHP and already consumes processing cycles.

If you found a serious vulnerability, you can either contact me in private via https://blueimp.net/ (my name is linked with my email address), or you can open another pull request with a fix, which is preferred.

I will not reenable the issues tracker for the simple reason that people misused it as a support request forum. With a project that popular, it became a full-time job to attend the issues so I deliberately chose to disable it.
I do not provide any support for this project anymore as stated in the [README](https://github.com/blueimp/jQuery-File-Upload#support).

**Pull request closed without merging**
