### PR TITLE
Fix 'non-well formed number notice' issue in PHP 7.2

### PR DESCRIPTION
**Pull request by codedeep**
try Fix 'non-well formed number notice' issue in PHP 7.2 or PHP 7.1

### CODE REVIEW

**Comment by blueimp** [comment]
Thanks for the contribution, @codedeep 
Could you provide a description on how to reproduce this issue?

**Comment by codedeep** [comment]
My actual settings:
PHP 7.2.11
post_max_size => 32M
upload_max_filesize => 32M
memory_limit => 128M

**Comment by blueimp** [comment]
Sorry, but I cannot reproduce any issue - neither with a `post_max_size` setting of `32M`, or an integer value of `9000000`.
The current code already does an explicit cast (using `$val = (int)$val;`), so I don't understand at the moment where the notice you encounter could come from.

**Comment by blueimp** [comment]
Closing due to no reply - @codedeep please feel free to reopen if you could clarify the issue from my question above.

**Pull request closed without merging**
