### PR TITLE
add load-image-scale to jquery.fileupload-image

### PR DESCRIPTION
**Pull request by Danter7**

### CODE REVIEW

**Comment by blueimp** [comment]
Thanks for your contribution @Danter7 
I'll merge this, but you'll also have to bump the `blueimp-load-image ` optional dependency to version `2.12.2`, else there won't be a separate `scale` module.

**Comment by veob** [comment]
Hey, @blueimp. Could you release version with this merge? That would be great.

**Comment by blueimp** [comment]
@veob done :)

**Comment by veob** [comment]
@blueimp, wow, such speed. Thank you! :)

**Pull request merged**
