### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by blueimp** [comment]
Thanks for your contribution.
However, since this is simply ignored by bower and might be used in the future, I'll rather keep it in the file.

**Comment by kkirsche** [comment]
Disagree with you considering bower hasn't had any real advancement and they are considering moving to NPM. bower/bower#1520 I think that's a very bad decision personally.

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by blueimp** [comment]
Sorry but I simply don't see a reason to remove the version information since it does work perfectly fine as it is.
It would be highly unlikely for the bower maintainers to throw a bug if the version field is present.

**Pull request closed without merging**
