### PR TITLE
Minor fixes to bootstrap/blueimp CSS URLs

### PR DESCRIPTION
**Pull request by noelcosgrave**

### CODE REVIEW

**Comment by blueimp** [comment]
Please have a look here:
https://www.google.com/search?q=protocol+relative+url

**Comment by noelcosgrave** [comment]
Please check the diffs in the commits before assuming I don't know what a relative URL is!

href="//netdna.bootstrapcdn.com...." is NOT a relative URL. It is not any type of valid URL. Also, as the file is being fetched from a CDN, a relative URL wouldn't do you any good, even if it was valid.

**Comment by noelcosgrave** [comment]
Forgot about scheme-relative URLs. My apologies.

**Comment by blueimp** [comment]
No worries, thanks for understanding. :)

**Pull request closed without merging**
