### PR TITLE
Add support for chunked upload on Android 4

### PR DESCRIPTION
**Pull request by DarrenInwood**
Adds feature detection for Android 4, forces this browser to use regular associative array instead of FormData, then adds an ajaxTransport to assemble the form POST manually.

### CODE REVIEW

**Comment by masud-technope** [comment]
This is a simple test comment for API testing. Please ignore it.

**Comment by joetidee** [comment]
Can you please update your documentation to mention that image previews will not work if the add: option is used when initializing the plugin?

**Comment by blueimp** [comment]
Given that this has been open for over a year and not been cleaned up, I'll close it for now.
I think doing client-side JPEG encoding is also not ideal.
I'll reconsider options to add Android support with a clean and updated pull request though.

**Comment by chandon** [comment]
After one year, still buggy, although there is a solution.

**Pull request closed without merging**
