### PR TITLE
adding import image from url

### PR DESCRIPTION
**Pull request by AndrewEastwood**
you can use this function to grab images by url and store it. You just need to invoke the ```importFromUrl``` with an url or set of urls and that's it :)

### CODE REVIEW

**Comment by blueimp** [comment]
Thanks for your contribution.
However at the moment I won't include this functionality, as I think it's rather out of scope of this project.

**Comment by AndrewEastwood** [comment]
omg

**Comment by blueimp** [comment]
No need to freak out, you know you can always continue to maintain your code in your own fork.

**Comment by AndrewEastwood** [comment]
that's true bat what's going on with the current?

**Comment by blueimp** [comment]
Are you referring to the security patch?

This refers to this patch here:
https://github.com/blueimp/jQuery-File-Upload/commit/5ee639504cb144aba4d04c9379fa670ed4ff8c44

Please also refer to my comment here:
https://github.com/blueimp/jQuery-File-Upload/pull/3381#issuecomment-69641256

**Comment by AndrewEastwood** [comment]
that's cool, I mean the security, but I didn't get how does it relate to this patch

**Pull request closed without merging**
