### PR TITLE
Updates Docs adds more hints for server setup

### PR DESCRIPTION
**Pull request by flobee**
Updates Docs adds more hints for server setup in htaccess file

### CODE REVIEW

**Comment by flobee** [comment]
Hi if you want new Coding Style (CS) you may check this commit which is not in this pull request: 
https://github.com/flobee/jquery-file-upload/commit/be620e9f4333f2225bcf4318af2ca6db89fdf0cf

**Comment by blueimp** [comment]
Thanks for your pull request @flobee.
Unfortunately I don't see the benefit of those contributions.
Maybe this would be better suited in a fork?
If there's an exact topic that this set of changes is about, I'll gladly add it to the Wiki.

**Comment by flobee** [comment]
Hi, the pull request shows changes for this:
https://github.com/blueimp/jQuery-File-Upload/pull/3472/commits/8d8b42bb8084982b2070a0d5a6fd657b6bca08ff
If this is not a benifit people maybe get lost :-/

All other listed here are not included. I'm not often send pull request, so maybe misunderstanding.
I forked already your project but will leave it as good as i can as is :-) Except coding style. This was a must have for me.

**Comment by blueimp** [comment]
You can keep the coding style or any other aspect in your fork whichever way you want. :)

I've added a note about the Apache Headers module to .htaccess file here: https://github.com/blueimp/jQuery-File-Upload/commit/fa04f7b0f8e04a15e397a6797c14a491c5d07fa4

As a recommendation, if you want maintainers to include your pull requests it's better to keep them atomic, with one set of focused changes.

**Pull request closed without merging**
